singleQuote: true
semi: true
printWidth: 100
tabWidth: 4
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
  - files:
      - '.prettierrc'
      - '*.json'
    options:
      tabWidth: 2
      printWidth: 80
  - files:
      - '*.scss'
    options:
      tabWidth: 2
      singleQuote: false
      trailingComma: none
  - files:
      - '*.md'
      - '*.mdx'
    options:
      proseWrap: preserve
      singleAttributePerLine: true
  - files:
      - '*.html'
    options:
      parser: 'angular'
      printWidth: 80
